### ISSUE TITLE
Does this support use with `List`?

### ISSUE THREAD

**Issue by forgot** [DominikButz/SwipeCellSUI#2]
The `README` states

>The purpose is to replace the default SwiftUI List .onDelete(perform: ...) modifier since its functionality is limited to deletion only and only works on List rows. Moreover, rows in an iOS 14 LazyVStack do not support swipe to reveal out of the box.

...but the example only uses the `ScrollView->LazyVStack` setup. Is this only intended for use with a `ScrollView->LazyVStack` setup, or should this work with `List` as well?

I've tried using it within a `List`, but it blocks the ability to scroll. If it's not intended to work with `List`, then I'm obviously using it wrong, which would explain the problem.

**Comment by DominikButz** [comment]
Hi Jesse, thanks for spotting this. I have just released a new version where the scrolling issue is fixed... However, I discovered that there are more issues with Lists unfortunately. When you add several buttons to the swipe-to-reveal menu, it seems that all button actions are triggered although only one is tapped. This does not happen when using this package in a ScrollView + LazyVStack.
You can try it out by downloading a new branch of the example repository I just created (see the link in the readme, then switch to the ListView-branch of the example) or just try it out in your own code after updating to the new version 2.1.2. 
A few options you have to work around this problem:
- consider to use ScrollView+ LazyVStack (it's more flexible anyway). If you need drag and drop, you can still use the .onDrag and onDrop modifiers (LazyVStacks don't support the edit mode provided by Apple for List views). 
- Don't use this package at all but make your project iOS 15 only. From iOS 15, swipe cell actions can be added through a new SwiftUI 3 feature.
