### ISSUE TITLE
can this work with navigationController hidesBarsOnSwipe set to True?

### ISSUE THREAD

**Issue by nickcom111** [DominikButz/SwipeCellSUI#4]
I've found that using this awesome package within a navigationController works perfectly well, but if you set navigationController?.hidesBarsOnSwipe = true (to mimic Safari app behaviour where the navigation title disappears on scroll) it interferes with the swipe gesture for this package, resulting in no left/right swipe functionality. 

Is there a suggested workaround for this which supports iOS14? Thanks.

**Comment by DominikButz** [comment]
Hi Nick,
thanks for the feedback. May I ask how you access the navigation controller? Do you use Introspect? 
regards
Dominik
